[package]
name = "scod"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.12"
wry = "0.54.1"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
shell-words = "1.1.1"
